apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: HelloSpringEKS
  name: HelloSpringEKS
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: HelloSpringEKS
    spec:
      containers:
      - image: naresh240/HelloSpringEKS
        name: HelloSpringEKS
        ports:
        - name: HelloSpringEKS
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: HelloSpringEKS
  name: HelloSpringEKS
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: HelloSpringEKS